config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"
  devise_for :users
  resources :books do
    member do
      post 'toggle_favorite', to: "books#toggle_favorite"
    end
  end
  resources :users
  resources :authors
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  ##Favourite book
  acts_as_favoritable

  ##Association
  has_many :books_categories, dependent: :destroy
  has_many :category, through: :books_categories
  belongs_to :author

  ##Search records
  def self.search(book)
    book ? where("name LIKE ?", "%#{book}%") : all
  end
end

app/models/books_category.rb
class BooksCategory < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books_categories, dependent: :destroy
  has_many :books, through: :books_categories
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  ##Favourite book
  acts_as_favoritor

  ##For assign a role
  rolify

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Callbacks
  after_create :assign_default_role

  def assign_default_role
    if self.email.eql?('admin@bookmanagement.com')
      self.add_role(:admin) if self.roles.blank?
    else
      self.add_role(:user) if self.roles.blank?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to authors_path, notice: 'Author was successfully added.'
    else
      redirect_to new_authors_path, errors: @author.errors.full_messages
    end
  end

  private

  def author_params
    params.require(:author).permit(:id, :name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.search(params[:name]).order('updated_at DESC')
    @favorite_books = current_user.favorited_by_type('Book')
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: 'Book was successfully added.'
    else
      redirect_to new_books_path, errors: @book.errors.full_messages
    end
  end

  def toggle_favorite
    @book = Book.find(params[:id])
    message = "#{@book.name} was Liked"
    if current_user.favorited?(@book)
      current_user.unfavorite(@book)
      message = "#{@book.name} was Disliked"
    else
      current_user.favorite(@book)
    end
    redirect_to root_path, notice: message
  end

  private

  def book_params
    params.require(:book).permit(:id, :name, :description, :publish_at, :author_id, category_ids: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully added.'
    else
      redirect_to new_category_path, errors: @category.errors.full_messages
    end
  end

  private

  def category_params
    params.require(:category).permit(:id, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    current_user.has_role?(:admin)
  end

  def user?
    current_user.has_role?(:user)
  end

  #---------------------page_index-------------------------
  def page_index(page, index, count=10)
    if page.present? && page.to_i > 1
      "<td>#{((page.to_i - 1) * count) + (index+1)}</td>".html_safe
    else
      "<td>#{index+1}</td>".html_safe
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def order_authors_by_name
    Author.order(:name)
  end

  def order_categories_by_name
    Category.order(:name)
  end
end

app/helpers/roles_helper.rb
module RolesHelper
  def has_role?(role)
    current_user && current_user.has_role?(role)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form|%>
  <% if admin? %>
    <div class="form-group row">
      <%= form.label :name, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-7">
        <%= form.text_field :name, autofocus: true, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to 'Cancel', authors_path, class:"btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/authors/index.html.erb
<% if user_signed_in? %>
  <% if admin? %>
    <%= link_to new_author_path, class: "btn btn-outline-primary" do %>
      <% 'New Author' %>
    <% end %>
  <% end %>
  <br>
  <br>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th><%= 'Author Name' %></th>
      </tr>
    </thead>
    <tbody>
      <% @authors.each_with_index do |author,index| %>
        <tr>
          <%= page_index(params[:page], index) %>
          <td><%= author.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/authors/new.html.erb
<div class="container h-100">
  <h2><%= 'New Author' %></h2>
  <br>
  <%= render 'form', author: @author %>
</div>

app/views/books/_book.html.erb
<div class="book" data-id="<%= book.id %>">
  <% if user_signed_in? %>
    <table class="table table-bordered table-hover">
      <tbody>
        <tr>
          <td><%= book.name %></td>
          <td><%= book.author.name %></td>
          <td><%= book.description %></td>
          <td><%= book.publish_at.to_date %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form|%>
  <% if admin? %>
    <div class="form-group row">
      <%= form.label :name, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-7">
        <%= form.text_field :name, autofocus: true, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <%= form.label :description, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-7">
        <%= form.text_area :description, autofocus: true, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <%= form.label :publish_at, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-7">
        <%= form.date_select :publish_at, autofocus: true, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <%= form.label :author, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-7">
        <%= form.collection_select :author_id, order_authors_by_name, :id, :name, { prompt: "Choose Author" }, {class: 'form-control'} %>
      </div>
    </div>
    <br>
    <div class="form-group row">
      <%= form.label 'Category', class: "col-sm-3 col-form-label" %>
      <div class="col-sm-7">
        <%= form.collection_select(:category_ids, order_categories_by_name, :id, :name, {}, {:multiple =>true, class: 'form-control'}) %>
      </div>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to 'Cancel', books_path, class:"btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/books/_like_button.html.erb
<div class="like-icon mx-2 <%='red' if current_user.favorited?(book) %>" data-id="<%= book.id %>">
  <% unless current_user.favorited?(book) %>
    Like
  <% else %>
    Dislike
  <% end %>
</div>

app/views/books/index.html.erb
<% if user_signed_in? %>
  <% if admin? %>
    <%= link_to new_book_path, class: "btn btn-outline-primary" do %>
      <%= 'New Book' %>
    <% end %> <br>
  <% end %><br>

  <div class="pull-left col-md-4">
    <%= form_tag books_path, method: 'get' do %>
      <%= text_field_tag :name, params[:name],class: 'input-search', placeholder: "Enter book name" %>
      <%= button_tag( type: "submit", class: 'btn-search search-icon-set') do%>
        <span>Search</span>
      <% end %>
    <% end %><br><br>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th><%= 'Book Name' %></th>
        <th><%= 'Author' %></th>
        <th><%= 'Description' %></th>
        <th><%= 'Category' %>
        <th><%= 'Publish At'%></th>
        <th><%= 'Status'%></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each_with_index do |book,index| %>
        <tr>
          <%= page_index(params[:page], index) %>
          <td><%= book.name %></td>
          <td><%= book.author.name %></td>
          <td><%= book.description %></td>
          <td>
            <% book.category.each do |category_name| %>
              <li><%= category_name.name %></li>
            <% end %>
          </td>
          <td><%= book.publish_at.to_date %></td>
          <% unless admin? %>
            <td>
            <%= button_to toggle_favorite_book_path(book), remote: true, method: :post do %>
              <%= render 'books/like_button', book: book %>
            <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table><br>
<% end %>

<% if current_user.roles[0].name.eql?('user') %>
  <div class="col-xs-12 col-sm-6">
    <h3>Liked Books</h3>
    <div class="favorites">
      <% @favorite_books.each do |book| %>
        <%= render 'book', book: book %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<div class="container h-100">
  <h2><%= 'New Book' %></h2>
  <br>
  <%= render 'form', book: @book %>
</div>

app/views/books/toggle_favorite.js.erb
var bookId = '<%= @book.id%>'

function toggleLikeButton(bookId, favoritedBook) {
  let likeButton = document.querySelector(`.like-icon[data-id='${bookId}']`)
  likeButton.classList.toggle('red');
  if (likeButton.classList.contains('red')) {
    const favoriteList = document.querySelector('.favorites');
    favoriteList.insertAdjacentHTML('beforeend', favoritedBook)
  }
  else {
    document.querySelector(`.favorite[data-id='${bookId}']`).remove()
  }
}

toggleLikeButton(bookId, '<%= j render "books/book", book: @book %>');

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form|%>
  <% if admin? %>
    <div class="form-group row"> 
      <%= form.label :name, class: "col-sm-3 col-form-label" %>
      <div class="col-sm-7">
        <%= form.text_field :name, autofocus: true, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to 'Cancel', categories_path, class:"btn btn-primary" %>   
    </div>
  <% end %>
<% end %>

app/views/categories/index.html.erb
<% if user_signed_in? %>
  <% if admin? %>
    <%= link_to new_category_path, class: "btn btn-outline-primary" do %>
      <% 'New Category' %>
    <% end %>
  <% end %>
  <br>
  <br>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th><%= 'Category Type' %></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category,index| %>
        <tr>
          <%= page_index(params[:page], index) %>
          <td><%= category.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/categories/new.html.erb
<div class="container h-100">
  <h2><%= 'New Category' %></h2>
  <br>
  <%= render 'form', category: @category %>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_user_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto my-2 my-lg-0">
        <li class="nav-item">
          <strong><%= link_to 'Home', root_path, class: "nav-link" %></strong>
        </li>
        <% if admin? %>
          <li class="nav-item">
            <strong><%= link_to 'Users',users_path, class: "nav-link" %></strong>
          </li>
          <li class="nav-item">
            <strong><%= link_to 'Authors', authors_path, class: "nav-link"  %></strong>
          </li>
          <li class="nav-item">
            <strong><%= link_to 'Categories', categories_path, class: "nav-link" %></strong>
          </li>
        <% end %>
      </ul>
    </div>
    <strong><div class="user-name-hi"><%= 'Hello' %>,</div> <%= current_user.email %> </strong> &ensp;
    <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm'  do %>
      Logout
    <% end %>
  </div>
</nav>

<% if admin? %>
  <h2 class= 'text-center' style= 'background-color: lightblue'>Admin Dashboard</h2><br/>
<% else %>
  <h2 class= 'text-center' style= 'background-color: lightblue'>User Dashboard</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages'%>
    <% if user_signed_in? %>
      <%= render 'layouts/user_header'%>
    <% end %>
    <% unless user_signed_in? %>
    <% end %>
    <main class="col-md-9 ms-sm-auto col-lg-12 px-md-4">
      <br>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th><%= 'UserEmail' %></th>
      <th><%= 'UserRole' %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user,index| %>
      <tr>
        <%= page_index(params[:page], index) %>
        <td><%= user.email %></td>
        <td><%= user.roles[0].name %></td>
      </tr>
    <% end %>
  </tbody>
</table>